// Geometry pass-through program for colored triangles
TRIANGLE void gs_swizzle(AttribArray<float4> position : POSITION)
{
  for (int i=0; i<position.length; i++) {
    emitVertex(position[i], float4(1,0.5,0.5,1):COLOR0);
  }
  restartStrip();
  for (int i=0; i<position.length; i++) {
    float4 newPosition = position[i].yxzw;
	emitVertex(newPosition:POSITION, float4(0.5,0.5,1,1):COLOR0);
  }
  restartStrip();
}